version: '3'
services:

  redis:
    # image: "redislabs/redismod:latest"
    image: "arm64v8/redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data1:/data

  redis2:
    # image: "redislabs/redismod:latest"
    image: "arm64v8/redis:latest"
    container_name: redis2
    ports:
      - "6380:6380"
    command: --port 6380
    volumes:
      - ./redis_data2:/data

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

  bankapp:
    image: bankapp
    container_name: bankapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - "./app/:/usr/src/app"
    environment:
      - REDIS_CONNECTION="redis://redis:6379"
      - CORE_POOLSIZE=20
