apiVersion: v1
kind: Secret
metadata:
  name: redb-masterdb-uri
type: Opaque
data:
  uri: cmVkaXM6Ly9hZG1pbjpDbDVyaG5RY0FYVEsyMUpLS1o3QmhkMDlhRm5MUGpLSVp5ODlDc3FBQUJUS09LM3ZAcmVkaXMtMTQzNzYucmVjLmRlbW8uc3ZjLmNsdXN0ZXIubG9jYWw6MTQzNzYK
